networks:
  my-network:
    driver: bridge

services:
  db:
    image: timescale/timescaledb:latest-pg17
    container_name: rbpi_db
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - timescale_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: rbpi_frontend
    ports:
      - "5173:5173"
    networks:
      - my-network

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: rbpi_backend
    restart: no
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      FAKE_DATA: ${FAKE_DATA}
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: rbpi_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    configs:
      - source: pgadmin_servers
        target: /pgadmin4/servers.json
      - source: pgadmin_pgpass
        target: /config/pgpass
        uid: "5050"
        gid: "5050"
        mode: 0600
    networks:
      - my-network

volumes:
  timescale_data:

configs:
  pgadmin_servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Baza IoT",
            "Group": "Serwers",
            "Host": "rbpi_db",
            "Port": 5432,
            "MaintenanceDB": "${DB_NAME}",
            "Username": "${DB_USER}",
            "SSLMode": "prefer",
            "PassFile": "/config/pgpass"
          }
        }
      }

  pgadmin_pgpass:
    content: |
      rbpi_db:5432:*:${DB_USER}:${DB_PASSWORD}
