networks:
  my-network:
    driver: bridge

services:
  db:
    image: timescale/timescaledb:latest-pg17
    container_name: rbpi_db
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - timescale_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: rbpi_frontend
    ports:
      - "5173:5173"
    networks:
      - my-network

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: rbpi_backend
    restart: no
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      FAKE_DATA: ${FAKE_DATA}
    networks:
      - my-network
volumes:
  timescale_data:
